In [4]:
from torch.nn import functional as F
import torch

Understanding f.pad

The padding size, by which to pad some dimensions of the input, are described starting from the last dimension and moving forward.

len(pad) / 2

dimensions of input will be padded.

For example:
- to pad only the last dimensions of a Tensor, `pad` has the form :

`(padding_left,padding_right)`

- to pad the last 2 dimensions of a Tensor, `pad` has the form:

`(padding_left, padding_right, padding_top, padding_bottom)`

- to pad the last 3 dimensions of a Tensor, `pad` has the form:

`(padding_left, padding_right, padding_top, padding_bottom, padding_front, padding_back)`


In [5]:
t2d = torch.empty(1, 10)

In [11]:
t2d.shape, t2d

(torch.Size([1, 10]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [10]:
p = F.pad(t2d, (1, 0), value=1)
p.shape, p

(torch.Size([1, 11]), tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [12]:
p = F.pad(t2d, (0, 1), value=1)
p.shape, p

(torch.Size([1, 11]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]))

In [13]:
p = F.pad(t2d, (1, 1), value=1)
p.shape, p

(torch.Size([1, 12]),
 tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]))

In [14]:
p = F.pad(t2d, (1, 1, 1, 1), value=1)
p.shape, p

(torch.Size([3, 12]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

In [ ]:
p = F.pad(t2d, (1, 1, 1, 1), value=1)
p.shape, p

In [15]:
t1d = torch.empty(10)

In [16]:
t1d

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
p = F.pad(t1d, (1, 0), value=1)
p.shape, p

(torch.Size([11]), tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [20]:
t1d = torch.ones(5)
t1d.shape, t1d

(torch.Size([5]), tensor([1., 1., 1., 1., 1.]))

In [22]:
p = F.pad(t1d, (1, 0), value=0)
p.shape, p

(torch.Size([6]), tensor([0., 1., 1., 1., 1., 1.]))

In [32]:
t3d = torch.ones(1, 5, 10)
t3d.shape, t3d

(torch.Size([1, 5, 10]),
 tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]))

In [33]:
p = F.pad(t3d, (1, 0), value=0)
p.shape, p

(torch.Size([1, 5, 11]),
 tensor([[[0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]))

In [34]:
p = F.pad(t3d, (0, 0, 1, 1), value=0)
p.shape, p

(torch.Size([1, 7, 10]),
 tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]))

In [35]:
p = F.pad(t3d, (0, 0, 1, 1, 1, 1), value=0)
p.shape, p

(torch.Size([3, 7, 10]),
 tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.


---

Padding mode:
See torch.nn.CircularPad2d, torch.nn.ConstantPad2d, torch.nn.ReflectionPad2d, and torch.nn.ReplicationPad2d for concrete examples on how each of the padding modes works. Constant padding is implemented for arbitrary dimensions. Circular, replicate and reflection padding are implemented for padding the last 3 dimensions of a 4D or 5D input tensor, the last 2 dimensions of a 3D or 4D input tensor, or the last dimension of a 2D or 3D input tensor.

---

mode – 'constant', 'reflect', 'replicate' or 'circular'. Default: 'constant'

value – fill value for 'constant' padding. Default: 0

In [47]:
p = F.pad(torch.tensor([[1, 2, 3]]), (2, 2),  mode="constant", value=0)
p

tensor([[0, 0, 1, 2, 3, 0, 0]])

value – fill value for 'reflect' padding.

In [48]:
p = F.pad(torch.tensor([[1, 2, 3]]), (2, 2),  mode="reflect")
p

tensor([[3, 2, 1, 2, 3, 2, 1]])

replicate

In [49]:
p = F.pad(torch.tensor([[1, 2, 3]]), (2, 2),  mode="replicate")
p

tensor([[1, 1, 1, 2, 3, 3, 3]])

circular

In [50]:
p = F.pad(torch.tensor([[1, 2, 3]]), (2, 2),  mode="circular")
p

tensor([[2, 3, 1, 2, 3, 1, 2]])

## Use cases

In [53]:
tokens = {
    "Hello": 1,
    "world": 2,
    "What": 3,
    "is": 4,
    "happening": 5,
    "here": 6,
    "everyone": 7
}

In [51]:
sentences = [
    "Hello world",
    "What is happening here everyone"
]

Since Tensors have to have consistent dimensions, the batch has to be stretched to the maximum length.

In [55]:
sentence_tokens = torch.Tensor([
    [1, 2, 0, 0, 0],
    [3, 4, 5, 6, 7]
])

We can create a pad mask to allow us to perform operations, only on the places that have genuine tokens.

To do that, we might create a bool where True represents the areas to mask. In our example, it might look like:

```python
[
    [False, False, True, True, True],
    [False, False, False, False, False]
]
```

We might expect to have a 1d tensor that represents the length of each row.

In [56]:
lens = torch.Tensor([2, 5])

In [60]:
lens.size(0)

2

In [62]:
seq_range = torch.arange(0, lens.max())
seq_range

tensor([0., 1., 2., 3., 4.])

In [67]:
expanded_lengths = seq_range.unsqueeze(0).expand(lens.size(0), int(lens.max()))
expanded_lengths

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])

In [71]:
sentence_mask = expanded_lengths >= lens.unsqueeze(-1)
sentence_mask

tensor([[False, False,  True,  True,  True],
        [False, False, False, False, False]])

We can use that to add a EOS token. For example, here I'm adding the EOS token represented by integer 100 to the end of each sequence:

In [79]:
eos = 100
eos_padded = F.pad(sentence_tokens, (0, 1), value=0) + eos * F.pad(sentence_mask, (0, 1), value=1)
eos_padded

tensor([[  1.,   2., 100., 100., 100., 100.],
        [  3.,   4.,   5.,   6.,   7., 100.]])

Or I can prepend a "beginning of sequence" (BOS) token as follows:

In [81]:
F.pad(eos_padded[:, :-1], (1, 0), value=101)

tensor([[101.,   1.,   2., 100., 100., 100.],
        [101.,   3.,   4.,   5.,   6.,   7.]])